source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BMBatteryManager_Example', :exclusive => true do
  pod "BMBatteryManager", :path => "../"
end

target 'BMBatteryManager_Tests', :exclusive => true do
  pod "BMBatteryManager", :path => "../"

  
end
